version: "3.7"
services:
  project_zomboid_dedicated_server:
    container_name: pz_server
    hostname: pz_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
      - "11119:11119/tcp"
    # volumes:
    #   # Server data
    #   - ./data:/home/steam/Zomboid
    #   # Workshop mods folder
    #   - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
